demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('app/news/', include('news.urls')),
    path('app/do/', include('to_do_list.urls')),
    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_do_list/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:pk>', views.delete_todo, name='delete_todo'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('status/<int:pk>', views.change_status, name='change_status'),
    path('edit/<int:pk>', views.edit_todo, name='edit_todo'),
]

to_do_list/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxLengthValidator


class ToDo(models.Model):
    title = models.CharField(max_length=80, verbose_name = 'Задача')
    status = models.BooleanField(default=False, verbose_name = 'Выполнено / Не выполнено')
    due_date = models.DateField(null=True, blank=True, verbose_name = 'Дата выполнения')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        # ordering = ['-pk']

to_do_list/forms.py
from django import forms
from .models import ToDo
from django.core.exceptions import ValidationError
from django.contrib.admin.widgets import AdminDateWidget

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'status', 'due_date']

to_do_list/views.py
from django.shortcuts import render, redirect
from .models import ToDo
from .forms import ToDoForm
from django.contrib import messages

def index(request):
    todo_items = ToDo.objects.all()
    if request.method == 'POST':
        new_todo = ToDo(title = request.POST['title'])
        new_todo.save()
        redirect('todo:index')
    unchecked = todo_items.filter(status=False)
    checked = todo_items.filter(status=True)
    dated =  todo_items.exclude(status=True).filter(due_date__isnull=False)
    return render(request, 'to_do_list/index.html',
    {'todo_items': todo_items, 'unchecked': unchecked, 'checked': checked, 'dated': dated})


def add_todo(request):
    if request.method == 'POST':
        title = request.POST['title']
        form = ToDoForm(request.POST)
        if form.is_valid():
            form.save()
        elif len(title) > 80:
            messages.error(request, 'Текст вашей задачи слишком длинный (максимум: 80 символов)!')
        else:
            messages.error(request, 'Вы ничего не написали!')
        return redirect('todo:index')
    else:
        form = ToDoForm()
    return render(request, 'to_do_list/index.html', {'form': form})


def edit_todo(request, pk):
    todo = ToDo.objects.get(pk=pk)
    form = ToDoForm(request.POST or None, instance=todo)
    if request.method == 'POST':
        title = request.POST['title']
        if form.is_valid():
            form.save()
            return redirect('todo:index')
        elif len(title) > 80:
            messages.error(request, 'Текст вашей задачи слишком длинный (максимум: 80 символов)!')
        else:
            messages.error(request, 'Вы ничего не написали!')

    else:
        form = ToDoForm()
    return render(request, 'to_do_list/edit.html', {'todo': todo, 'form': form})


def change_status(request, pk):
    todo_item = ToDo.objects.get(id=pk)
    if todo_item.status == False:
        todo_item.status = True
        todo_item.due_date = None
    else:
        todo_item.status = False
    todo_item.save()
    return redirect('todo:index')


def delete_todo(request, pk):
    todo_item = ToDo.objects.get(id=pk)
    todo_item.delete()
    return redirect('todo:index')

to_do_list/templates/to_do_list/edit.html
{% extends "base.html" %}


{% block title %}Изменить задачу :: {{ block.super }}{% endblock %}
{% block css%}{% endblock %}
{% block header %}

<div class="container-fluid">
    <div class="row pt-5 ">
        <div class="col-12 text-primary text-center">
        <h1><b>Изменить задачу</b></h1>
        </div>
    </div>
</div>

{% endblock %}

{% block main %}


<div class="container-fluid mb-3">
        <div class="row justify-content-center">
            <div class="col-9">
                <form action="{% url 'todo:edit_todo' todo.id %}" method="POST">
                    {% csrf_token %}
                <div class="d-flex">
                            <label for="id_title"></label>
                            <input type="text" name="title" class="form-control me-2" id="id_title" value="{{ todo.title|capfirst }}">
                            <label for="due_date"></label>
                            <input type="date" class="form-control" name="due_date" id="due_date" value="{{ todo.due_date|date:"Y-m-d" }}" style="visibility: hidden; width: 1px; padding: 0;">
                            <label class="input-group-addon btn btn-outline-primary me-2" for="due_date" id="due_date" title="Установить дату">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-plus" viewBox="0 0 16 16">
                                    <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
                                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                                </svg>
                            </label>
                            <button type="submit" class="btn btn-primary"><b>Обновить</b></button>
                            </div>
                                                        <label for="id_status class="form-check-label pt-2 for="id_status">
                            <input class="form-check-input" name="status" type="checkbox" id="id_status" {% if todo.status %} checked="checked" {% endif %}">
                            &nbsp;Выполнено
                            
                </form>
            </div>
        </div>
</div>

{% endblock %}

to_do_list/templates/to_do_list/index.html
{% extends "base.html" %}
{% load static %}
{% load todo_extras %}


{% block title %}Список задач :: {{ block.super }} {% endblock %}
{% block css%}{% endblock %}
{% block header %}

<div class="container-fluid">
    <div class="row pt-5 mb-4">
        <div class="col-12 text-primary text-center">
        <h1><b>Список задач</b></h1>
        </div>
    </div>
</div>

{% endblock header %}

{% block main %}



<div class="container-fluid mb-3">
    <div class="row justify-content-center">
        <div class="col-9">
            <form action="{% url 'todo:add_todo' %}" class="d-flex" method="POST" role="toolbar">
                {% csrf_token %}
                
                

                    <input class="form-control me-2" type="text" name="title" id="title" placeholder="Введите задачу...">
                    <label for="due_date"></label>
                    <input type="date" class="form-control" name="due_date" id="due_date" style="visibility: hidden; width: 1px; padding: 0;">
                    <label class="input-group-addon btn btn-outline-primary me-2" type="image/x-icon" for="due_date" id="due_date" title="Установить дату">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-plus" viewBox="0 0 16 16">
                            <path d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
                            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                        </svg>
                    
                    </label>

                    

                
                <button type="submit" class="btn btn-primary"><b>Добавить</b></button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block todo_items %}

<div class="container-fluid">
    <div class="row pt-2 justify-content-center">
        <div class="col-9">
            <nav>
                <div class="nav nav-pills" id="nav-tab" role="tablist">
                    <button class="nav-link active" id="nav-all-tab" data-bs-toggle="tab" data-bs-target="#nav-all" type="button" role="tab" aria-controls="nav-all" aria-selected="true">Всё</button>
                    <button class="nav-link" id="nav-unchecked-tab" data-bs-toggle="tab" data-bs-target="#nav-unchecked" type="button" role="tab" aria-controls="nav-unchecked" aria-selected="false">Не выполнено</button>
                    <button class="nav-link" id="nav-checked-tab" data-bs-toggle="tab" data-bs-target="#nav-checked" type="button" role="tab" aria-controls="nav-checked" aria-selected="false">Выполнено</button>
                    <button class="nav-link" id="nav-due-tab" data-bs-toggle="tab" data-bs-target="#nav-due" type="button" role="tab" aria-controls="nav-due" aria-selected="false">По дате</button>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab" tabindex="0">
                    <ul class="list-group pt-3">
                        {% for todo in todo_items reversed %}
                        <li class="list-group-item">
                            {% if todo.status == False%}

                                <a href="{% url 'todo:change_status' todo.id %}" title="Отметить как выполнено" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/square.svg' %}" width="16" height="16"></a>
                                </a>&nbsp;

                                <item><strong>{{ todo.title|capfirst }}</strong></item>{% if todo.due_date %}&nbsp;<span class="badge bg-primary">{{ todo.due_date }}</span>{% endif %}&nbsp;

                                <a href="{% url 'todo:edit_todo' todo.id %}" title="Изменить" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/pencil-fill.svg' %}" width="16" height="16"></a>

                                <a href="{% url 'todo:delete_todo' todo.id %}" title="Удалить" class="text-decoration-none" style="float:right">
                                <img src="{% static 'bootstrap/img/trash-fill.svg' %}" width="16" height="16"></a>

                            {% else %}
                                <a href="{% url 'todo:change_status' todo.id %}" title="Отметить как невыполнено" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/check-square.svg' %}" width="16" height="16"></a>
                                </a>&nbsp;
                                <item class="text-black-50"><strong>{{ todo.title|capfirst }}</strong></item>&nbsp;

                                <a href="{% url 'todo:edit_todo' todo.id %}" title="Изменить" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/pencil-fill.svg' %}" width="16" height="16"></a>

                                <a href="{% url 'todo:delete_todo' todo.id %}" title="Удалить" class="text-decoration-none" style="float:right">
                                <img src="{% static 'bootstrap/img/trash-fill.svg' %}" width="16" height="16"></a>
                            {% endif %}
                        </li>
                        {% empty %}
                            <div class="text-primary">
                                <h3><b>Похоже, здесь ничего нет</b></h3>
                            </div>
                        {% endfor %}
                    </ul>
                </div>
                <div class="tab-pane fade" id="nav-unchecked" role="tabpanel" aria-labelledby="nav-unchecked-tab" tabindex="0">
                    <ul class="list-group pt-3">
                        {% for todo in todo_items reversed %}
                            {% if todo.status == False %}
                            <li class="list-group-item">
                                
                                <a href="{% url 'todo:change_status' todo.id %}" title="Отметить как выполнено" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/square.svg' %}" width="16" height="16"></a>
                                </a>&nbsp;

                                <item><strong>{{ todo.title|capfirst }}</strong></item>{% if todo.due_date %}&nbsp;<span class="badge bg-primary">{{ todo.due_date }}</span>{% endif %}&nbsp;

                                <a href="{% url 'todo:edit_todo' todo.id %}" title="Изменить" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/pencil-fill.svg' %}" width="16" height="16"></a>

                                <a href="{% url 'todo:delete_todo' todo.id %}" title="Удалить" class="text-decoration-none" style="float:right">
                                <img src="{% static 'bootstrap/img/trash-fill.svg' %}" width="16" height="16"></a>
                                
                            </li>  
                            {% endif %}
                        {% endfor %}
                    </ul>
                    {% if not unchecked %}
                        <div class="text-primary">
                        <h3><b>Похоже, здесь ничего нет</b></h3>
                        </div>
                    {% endif %}
                </div>
                <div class="tab-pane fade" id="nav-checked" role="tabpanel" aria-labelledby="nav-checked-tab" tabindex="0">
                    <ul class="list-group pt-3">
                        {% for todo in todo_items reversed %}
                            {% if todo.status == True %}
                            <li class="list-group-item">
                                
                                <a href="{% url 'todo:change_status' todo.id %}" title="Отметить как невыполнено" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/check-square.svg' %}" width="16" height="16"></a>
                                </a>&nbsp;
                                <item class="text-black-50"><strong>{{ todo.title|capfirst }}</strong></item>&nbsp;

                                <a href="{% url 'todo:edit_todo' todo.id %}" title="Изменить" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/pencil-fill.svg' %}" width="16" height="16"></a>

                                <a href="{% url 'todo:delete_todo' todo.id %}" title="Удалить" class="text-decoration-none" style="float:right">
                                <img src="{% static 'bootstrap/img/trash-fill.svg' %}" width="16" height="16"></a>
                                
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    {% if not checked %}
                        <div class="text-primary">
                        <h3><b>Похоже, здесь ничего нет</b></h3>
                        </div>
                    {% endif %}
                </div>
                <div class="tab-pane fade" id="nav-due" role="tabpanel" aria-labelledby="nav-due-tab" tabindex="0">
                    <ul class="list-group pt-3">
                        {% for todo in todo_items|order_by:"due_date" %}
                            {% if todo.due_date and todo.status == False %}

                            <li class="list-group-item">

                                <a href="{% url 'todo:change_status' todo.id %}" title="Отметить как выполнено" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/square.svg' %}" width="16" height="16"></a>
                                </a>&nbsp;

                                <item><strong>{{ todo.title }}</strong></item>{% if todo.due_date %}&nbsp;<span class="badge bg-primary">{{ todo.due_date }}</span>{% endif %}&nbsp;

                                <a href="{% url 'todo:edit_todo' todo.id %}" title="Изменить" class="text-decoration-none">
                                <img src="{% static 'bootstrap/img/pencil-fill.svg' %}" width="16" height="16"></a>

                                <a href="{% url 'todo:delete_todo' todo.id %}" title="Удалить" class="text-decoration-none" style="float:right">
                                <img src="{% static 'bootstrap/img/trash-fill.svg' %}" width="16" height="16"></a>

                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    {% if not dated %}
                        <div class="text-primary">
                        <h3><b>Похоже, здесь ничего нет</b></h3>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


<br>
<br>

{% endblock %}