demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('app/news/', include('news.urls')),
    path('app/do/', include('to_do_list.urls')),
    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from news.views import HomeNews, NewsByCategory, ViewNews, CreateNews

app_name = 'news'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', HomeNews.as_view(), name='home'),
    # path('category/<int:category_id>/', views.get_category, name='category'),
    path('category/<int:category_id>/', NewsByCategory.as_view(), name='category'),
    # path('<int:news_id>/', views.view_news, name='view_news'),
    path('<int:pk>/', ViewNews.as_view(), name='view_news'),
    # path('add-news/', views.add_news, name="add_news"),
    path('add-news/', CreateNews.as_view(), name="add_news"),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('contact/', views.contact, name='contact'),




    # TO DELETE BELOW!
    path('test/', views.test, name='test')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Demo Apps{% endblock %}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
     {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> {% endcomment %}
{% block css%}<link href="{% static 'css/style.css' %}" rel="stylesheet">{% endblock %}
</head>
<body>
{% include 'inc/_navbar.html' %}

{% block header %}{% endblock %}

{% block main %}{% endblock %}

{% block messages %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-9">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert alert-danger" role="alert">
                        {{ message }}
                    </div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message|safe }}
                    </div>
                {% endif %}
            {% endfor %}
            {% endif%}
        </div>
    </div>
</div>    
    
{% endblock %}

{% block todo_items %}{% endblock %}
{% block pagination %}

<div class="container-fluid mb-3">
    <div class="row">
        <div class="col-md-2 pt-3">
        </div>
        <div class="col-md-10 pt-3">
            {% if page_obj.has_other_pages %}
                <nav aria-label="...">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Назад</a>
                        </li>
                        {% endif %}
                        {% for p in page_obj.paginator.page_range %}
                            {% if page_obj.number == p %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?page={{ p }}">{{ p }}<span class="sr-only"></span></a>
                            </li>
                            {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                            </li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1">Вперёд</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block feedback %}
{% if title or news_item.title %}
<div class="container-fluid text-end">
    <small><a class="text-decoration-none mt-auto p-2" href="{% url 'news:contact' %}"<b>Обратная связь</b></a></small>
    {% comment %} <div class="row ">
            <a href="{% url 'news:contact' %}" class="text-muted style: none"><b>Обратная связь</b></a>
    </div> {% endcomment %}
</div>
{% endif %}
{% endblock %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script> {% endcomment %}
</body>
</html>