common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.start, name='start'),
    path('test/', views.test, name='test')
]

demo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('app/news/', include('news.urls')),
    path('app/do/', include('to_do_list.urls')),
    path('captcha/', include('captcha.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from news.views import HomeNews, NewsByCategory, ViewNews, CreateNews

app_name = 'news'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', HomeNews.as_view(), name='home'),
    # path('category/<int:category_id>/', views.get_category, name='category'),
    path('category/<int:category_id>/', NewsByCategory.as_view(), name='category'),
    # path('<int:news_id>/', views.view_news, name='view_news'),
    path('<int:pk>/', ViewNews.as_view(), name='view_news'),
    # path('add-news/', views.add_news, name="add_news"),
    path('add-news/', CreateNews.as_view(), name="add_news"),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('contact/', views.contact, name='contact'),




    # TO DELETE BELOW!
    path('test/', views.test, name='test')
]

to_do_list/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:pk>', views.delete_todo, name='delete_todo'),
    path('add_todo/', views.add_todo, name='add_todo'),
    path('status/<int:pk>', views.change_status, name='change_status'),
    path('edit/<int:pk>', views.edit_todo, name='edit_todo'),
]

templates/inc/_navbar.html
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'common:start' %}"><b>Apps</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'todo:index' %}"><b>To Do List</b></a>
            <a class="nav-link active" aria-current="page" href="{% url 'news:home' %}"><b>News</b></a>
            {% comment %} {% if news or news_item %}
                {% if request.user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'news:add_news' %}"><b>Добавить новость</b></a>
                {% endif %}
            {% endif %} {% endcomment %}
        </div>      
    </div>
    <span class="navbar-text">
        {% if title or news_item.title %}
            {% if request.user.is_authenticated %}
                <a href="{% url 'news:add_news' %}"><b>Написать новость, {{ user.username }}?</b></a> | <a href="{% url 'news:logout' %}"><b>Выйти</b></a>
            {% else %}
                <a href="{% url 'news:login' %}"><b>Войти</b></a> | <a href="{% url 'news:register' %}"><b>Регистрация</b></a>
            {% endif %}
        {% endif %}
    </span>
  </div>
</nav>